### PR TITLE
Adds documentation for SphinxMeta

### PR DESCRIPTION
**Pull request by willkg**
This is what I sussed out of the code and tests.  Any additional thoughts would be super.  Figured it's best to document it in the README since we don't have other docs and adding additional docs seems overkill.

r?

### CODE REVIEW

**Comment by jsocol** [comment]
Looks clear and readable to me. Not sure if you want to wait for Erik but I say go for it.

**Comment by willkg** [comment]
I only worked on weight and excerpt/highlight related stuff.  I need someone else to do a correctness/completeness check.

**Comment by willkg** [comment]
Also, this is just docs-related.  It doesn't matter if this pull request gets worked through immediately.

**Comment by rlr** [comment]
This looks good to me!

**Comment by erikrose** [comment]
Looks good to me! r+. If we notice more, we can add more.

**Pull request merged**
